global:
  smtp_smarthost: 'crediya-mailhog:1025'
  smtp_from: 'alertmanager@crediya.local'
  smtp_require_tls: false

route:
  receiver: 'web.hook'

receivers:
- name: 'web.hook'
  email_configs:
  - to: 'admin@crediya.local'
